---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number to validate
        required: true
        type: number

jobs:
  validate:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: 🏷 Verify PR has a valid label
        uses: klaasnicolaas/action-pr-labels@v3.1.1
        with:
          pr-number: >-
            ${{ github.event.pull_request.number || inputs.pr_number }}
          valid-labels: >-
            breaking-change, bugfix, documentation, enhancement, sync,
            refactor, performance, new-feature, maintenance, ci, dependencies
